version: '3'

services:
  wordpress_db:
    image: mysql:5.7
    volumes:
      - wordpress_db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
  wordpress:
    depends_on:
      - wordpress_db
    image: wordpress:5.9
    image: wordpress:5.9
    ports:
      - "8000:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: wordpress_db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
    volumes:
      - ./wp-config.php:/var/www/html/wp-config.php

  rails_db:
    image: postgres:13.4
    environment:
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=postgres'
    volumes:
      - 'rails_db_data:/var/lib/postgresql/data'
  redis:
    image: redis:6.0
    command: redis-server
    ports:
      - 6379:6379
    volumes:
      - redis:/data
  app:
    build: .
    command: >
      bash -c "rm -f tmp/pids/server.pid &&
        bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
      - '3000:3000'
    volumes:
      - '.:/app'
    environment:
      - 'RAILS_ENV=development'
      - 'DATABASE_PORT=5432'
      - 'DATABASE_HOST=rails_db'
    tty: true
    stdin_open: true
    depends_on:
      - rails_db
      - redis
    links:
      - rails_db

volumes:
  wordpress_db_data:
  rails_db_data:
  redis:
